project:
  type: book
  output-dir: docs

book:
  title: "Biostatistics and Data Analysis for Zoologists"
  author: "Thiyanga S. Talagala"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "03-chap3.qmd"
    - "04-chap4.qmd"
    - "05-chap5.qmd"
    - "06-chap6.qmd"
    - "07-chap7.qmd"
    - "08-chap8.qmd"
    - "refs.qmd"
  sidebar:
    style: "docked"

bibliography: thesisrefs.bib
csl: american-statistical-association.csl


format:
  monashthesis-html: default

